name: Continuous Delivery
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          python -m pytest test_organizador.py -v

  deliver:
    runs-on: ubuntu-latest
    needs: testes
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando continuous delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            main.py
            README.md
            organizador.py
            test_organizador.py

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: projetozipado
      - name: Display structure of downloaded files
        run: ls -R

  docker:
    runs-on: ubuntu-latest
    needs: testes
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      #  - name: Login to Docker Hub
      #    uses: docker/login-action@v3
      #    with:
      #      username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
      - name: Build Docker image
        run: docker build .
