name: Continuous Delivery
on:
  push:
    branches:
      - main

permissions: # permissões mínimas necessárias
  contents: read

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando continuous delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            main.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: projetozipado.zip
      - name: Display structure of downloaded files
        run: ls -R
