name: Continuous Delivery
on:
  push:
    branches:
      - main

# permissions: # permissões mínimas necessárias (com espaço após #)
# contents: read

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando continuous delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            main.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: projetozipado
      - name: Display structure of downloaded files
        run: ls -R

  docker:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          # push: true
          # tags: user/app:latest
