name: Continuous Integration
permissions:
  contents: read
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Lint Python code
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Run Discord Webhook
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"

